### ISSUE TITLE
Calendar blue text doesn't change color.

### ISSUE THREAD

**Issue by Orca2040** [brianeroth/KleenSlate#38]
The blue text on the calendar doesn't change color when hovering over or on the current date, number isn't visible.

![calendar](https://cloud.githubusercontent.com/assets/3665200/12709118/d964f944-c865-11e5-82a1-9e1757151302.PNG)

**Comment by TomPed** [comment]
@Orca2040 do you think that the text color should change to like a darker grey? Kinda like the color of the arrows to change the month?

**Comment by Orca2040** [comment]
@TomPed A white or off-white would look cleaner, I think.

**Comment by TomPed** [comment]
Sounds good to me, what do you think @brianeroth?

**Comment by TomPed** [comment]
I'll take that as a good. :angry:!
