### ISSUE TITLE
Clicking around the home screen

### ISSUE THREAD

**Issue by TomPed** [brianeroth/KleenSlate#39]
When you click these buttons a nice looking text box should appear to give some info about the topic. These buttons:
![screen shot 2016-02-01 at 12 05 01 am](https://cloud.githubusercontent.com/assets/11602092/12709217/76d7efae-c877-11e5-8944-c55305b4c07d.png)

**Comment by brianeroth** [comment]
These will go to separate pages, and are part of #7
